### ISSUE TITLE
Week one mvp

### ISSUE THREAD

**Issue by emo8355** [cee-elle/fswd-agile-final-project#6]
user:
input type of food
- get back a list of recipe

**Comment by SkylarZhao6** [comment]
According to what we put down on the plan of action, week one should only ask for calories.

**Comment by emo8355** [comment]
> According to what we put down on the plan of action, week one should only ask for calories input.

no, no longer XD

**Comment by SkylarZhao6** [comment]
Did Cindy approve that?

**Comment by jaime-deng** [comment]
To the extent of my knowledge, only the project manager, Cindy, can make changes to the original plan of action. Since no such event has occurred, our week one mvp should remain consistent with providing a result based on an input of calories from the user.

**Comment by dl90** [comment]
we can get the caloires with x.recipie.calories 
i guess we need to do some server side things to the data we get back from the api so it matches around the calories user inputs.

**Comment by emo8355** [comment]
The api is able to get the food by its calorie, and it is count by portion. as long as the req.body is formatted correctly, we can get the food by dietary.

req.body
{
   q: chicken.
   calories: 100-300
}
